### ISSUE TITLE
Can't find assets

### ISSUE THREAD

**Issue by cjsb** [Unity-Technologies/Unity-Experimental-DXR#1]
Hi,

I just clone the project but there is no assets on the unity editor. What should I do to run the project?

Thank you.

**Comment by cjsb** [comment]
Also, I can't find the project directory to open on unity.

**Comment by sasa42** [comment]
add Unity.exe to Unity Hub.
Then create New Unit Project with DXR High-Definition RP (Preview) Template in Unity Hub
