### ISSUE TITLE
Renderer type "SkinnedMeshRenderer" not supported.

### ISSUE THREAD

**Issue by TianZhongJun** [Unity-Technologies/Unity-Experimental-DXR#12]
![123](https://user-images.githubusercontent.com/19504740/56076710-af936d00-5e06-11e9-9284-0e1c6da01d92.PNG)

Well, it seems ray tracing can not render SkinnedMeshRenderer component. There is no ray tracing reflection for the human, but his weapon has.

**Comment by sebastienlagarde** [comment]
Hi, this is expected, this experimental version don't support skinned mesh as explain in the manual.
