### ISSUE TITLE
"This app can't run on your PC"

### ISSUE THREAD

**Issue by marshmatter** [Unity-Technologies/Unity-Experimental-DXR#3]
I'm hitting a Windows 10 "This app can't run on your PC" error. 

![image](https://user-images.githubusercontent.com/4061861/55587600-af55ec00-56f9-11e9-889e-4c1bb12d9bd2.png)

Windows 10 Pro, version 1809 
RTX 2060, driver version 419.67

**Comment by copy0660** [comment]
For whatever reason when downloading the zip, the .exe is just 1 kb of size. You can manually download the Unity.exe (100+ MB) from the repo. Then you'll probably hit the other issue the other person posted (but that's just another problem).

**Comment by marshmatter** [comment]
Ok great, will give it a shot. In trying to doing all kinds of admin privileges acrobatics I didn't even notice the 1kb exe size.

**Comment by marshmatter** [comment]
I completely forgot the GitHub generated .zip download won't include LFS managed files. Doing a proper clone now.
