### ISSUE TITLE
Support for Titan V?

### ISSUE THREAD

**Issue by oscarbg** [Unity-Technologies/Unity-Experimental-DXR#6]
Hi,
can you list supported GPUs for this build..
are all DXR compatible GPUs supported like Titan V (and even Pascal GPUs with upcoming drivers) or only newer Turing GPUs supported..
thanks..

**Comment by sebastienlagarde** [comment]
Hi. All NVidia graphic card with RTX support should be supported. We don't have list to provide. Check NVidia website for graphic card specification. Thanks
